version: '3.8'
services:
  nest_db:
    build:
      dockerfile: ./docker/MysqlDockerfile
      context: .
    container_name: nest_db
    ports:
      - '3306:3306'
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
  api:
    container_name: nest_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    restart: always
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - nest_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: '${DATABASE_HOST}'
      PMA_USER: '${DATABASE_USER}'
      PMA_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - nest_db
